### ISSUE TITLE
Is this still a project ?

### ISSUE THREAD

**Issue by rrey** [mattermost/terraform-provider-mattermost#1]
Because I'd love to have a provider to automate channels creation for a standard deployment pattern.

**Comment by cpanato** [comment]
@rrey thanks for your issue. I will check internally and get back to you

but you can use something that I'm working on: https://github.com/cpanato/mattermost-gitops

**Comment by cpanato** [comment]
said that, if you are interested to contribute to this project I can help you out

**Comment by rrey** [comment]
Ok Thx 
Learning Go to work on p
Terraform providers is in my todo for some time :)
We’ll see if I find time ! 🤞
